import { type SupabaseClient } from '@supabase/supabase-js';
import { trackUsage } from '../lib/usage-tracker.js';
import { incrementSpending } from '../lib/spending-guard.js';

// ---------------------------------------------------------------------------
// PDF generation handler
// Generates a structured HTML document (placeholder for real PDF via pdf-lib)
// and uploads it to the 'exports' bucket.
// ---------------------------------------------------------------------------
export async function handlePdfGeneration(
  supabase: SupabaseClient,
  payload: Record<string, unknown>,
  userId: string,
  companyId: string,
): Promise<Record<string, unknown>> {
  const projectId = payload.project_id as string;
  const designRunId = payload.design_run_id as string;

  // 1. Load design_run planner_json
  const { data: run, error: runErr } = await supabase
    .from('design_runs')
    .select('planner_json')
    .eq('id', designRunId)
    .single();

  if (runErr || !run) {
    throw new Error(`Failed to load design_run ${designRunId}: ${runErr?.message}`);
  }

  const plannerJson = run.planner_json as Record<string, unknown> | null;
  if (!plannerJson) {
    throw new Error('No planner_json found — run planner first');
  }

  // 2. Load project info
  const { data: project, error: projErr } = await supabase
    .from('projects')
    .select('name, address, climate_zone')
    .eq('id', projectId)
    .single();

  if (projErr || !project) {
    throw new Error(`Failed to load project ${projectId}: ${projErr?.message}`);
  }

  // 3. Generate structured HTML (placeholder for pdf-lib)
  const plantPalette = (plannerJson.plant_palette as Array<Record<string, unknown>>) ?? [];
  const materials = (plannerJson.materials as Array<Record<string, unknown>>) ?? [];
  const maintenanceNotes = (plannerJson.maintenance_notes as string[]) ?? [];
  const style = (plannerJson.style as string) ?? '';
  const budget = (plannerJson.estimated_budget as string) ?? '';

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Landscape Plan — ${escapeHtml(project.name)}</title>
  <style>
    body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #333; }
    h1 { color: #2d5016; border-bottom: 2px solid #2d5016; padding-bottom: 8px; }
    h2 { color: #3a6b1e; margin-top: 32px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th, td { border: 1px solid #ccc; padding: 8px 12px; text-align: left; }
    th { background: #f0f7e8; }
    ul { padding-left: 20px; }
    .meta { color: #666; font-size: 0.9em; }
    .footer { margin-top: 48px; font-size: 0.8em; color: #999; border-top: 1px solid #eee; padding-top: 16px; }
  </style>
</head>
<body>
  <h1>Landscape Plan</h1>
  <p><strong>Project:</strong> ${escapeHtml(project.name)}</p>
  <p class="meta">Address: ${escapeHtml(project.address ?? 'N/A')} | Climate Zone: ${escapeHtml(project.climate_zone ?? 'N/A')}</p>
  ${style ? `<p><strong>Style:</strong> ${escapeHtml(style)}</p>` : ''}
  ${budget ? `<p><strong>Estimated Budget:</strong> ${escapeHtml(budget)}</p>` : ''}

  <h2>Plant Palette</h2>
  ${plantPalette.length > 0 ? `
  <table>
    <thead>
      <tr><th>Plant</th><th>Botanical</th><th>Qty</th><th>Spacing</th><th>Sun</th><th>Water</th></tr>
    </thead>
    <tbody>
      ${plantPalette.map((p) => `
      <tr>
        <td>${escapeHtml(String(p.common_name ?? ''))}</td>
        <td><em>${escapeHtml(String(p.botanical_name ?? ''))}</em></td>
        <td>${p.quantity_estimate ?? ''}</td>
        <td>${escapeHtml(String(p.spacing_inches ?? ''))}</td>
        <td>${escapeHtml(String(p.sun ?? ''))}</td>
        <td>${escapeHtml(String(p.water ?? ''))}</td>
      </tr>`).join('')}
    </tbody>
  </table>` : '<p>No plants specified.</p>'}

  <h2>Materials</h2>
  ${materials.length > 0 ? `
  <table>
    <thead>
      <tr><th>Material</th><th>Quantity</th><th>Est. Cost</th></tr>
    </thead>
    <tbody>
      ${materials.map((m) => `
      <tr>
        <td>${escapeHtml(String(m.name ?? ''))}</td>
        <td>${escapeHtml(String(m.quantity ?? ''))}</td>
        <td>${escapeHtml(String(m.estimated_cost ?? ''))}</td>
      </tr>`).join('')}
    </tbody>
  </table>` : '<p>No materials specified.</p>'}

  <h2>Maintenance Notes</h2>
  ${maintenanceNotes.length > 0 ? `
  <ul>
    ${maintenanceNotes.map((n) => `<li>${escapeHtml(n)}</li>`).join('')}
  </ul>` : '<p>No maintenance notes.</p>'}

  <div class="footer">
    <p>Generated by Shrubb — AI Landscape Proposals</p>
  </div>
</body>
</html>`;

  // 4. Upload to 'exports' bucket (company-scoped path)
  const fileId = crypto.randomUUID();
  const storagePath = `${companyId}/${projectId}/${fileId}.html`;

  const { error: uploadErr } = await supabase.storage
    .from('exports')
    .upload(storagePath, Buffer.from(html, 'utf-8'), {
      contentType: 'text/html',
      upsert: false,
    });

  if (uploadErr) {
    throw new Error(`Failed to upload PDF/HTML: ${uploadErr.message}`);
  }

  // 5. Create design_asset record
  const { data: asset, error: assetErr } = await supabase
    .from('design_assets')
    .insert({
      design_run_id: designRunId,
      asset_type: 'pdf',
      storage_path: storagePath,
      metadata: { format: 'html', placeholder: true },
    })
    .select('id')
    .single();

  if (assetErr || !asset) {
    throw new Error(`Failed to create design_asset: ${assetErr?.message}`);
  }

  // 6. Track usage (company-scoped)
  const pdfCost = 0.001; // nominal tracking cost
  await trackUsage(supabase, {
    user_id: userId,
    company_id: companyId,
    project_id: projectId,
    run_type: 'pdf',
    tokens_in: 0,
    tokens_out: 0,
    image_count: 0,
    estimated_cost_usd: pdfCost,
    provider: 'internal',
    model: 'pdf-gen',
  });

  await incrementSpending(supabase, companyId, Math.ceil(pdfCost * 100));

  console.log(`[pdf_generation] design_run ${designRunId} — asset ${asset.id}`);

  return { asset_id: asset.id };
}

// ---------------------------------------------------------------------------
// Utility: basic HTML escaping
// ---------------------------------------------------------------------------
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
